[package]
name = "models-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
const-fnv1a-hash = "1.1.0"
proc-macro2 = { version = "1.0.101", features = ["nightly"] }
quote = "1.0.41"
syn = "2.0.106"

[lib]
proc-macro = true
